name: Build and Release Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK 21 (OpenJDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: ls -la
        run: ls -la

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.jar
          token: ${{ secrets.PAT_TOKEN }}
