name: VillagerReputationTweaks
version: ${version}
main: com.kami.VillagerReputationTweaks
description: Gives several options for tweaking how villager reputations are managed for players on servers.
author: Kamisama
website: https://github.com/Ujjwal-Shekhawat
api-version: ${minecraft_version}

# Commands used by this
commands:
  trademode:
    description: "Gets the trade mode currently being used on the server"
    usage: "/trademode get | set <best-trades|worst-trades|shared-trades|one-time-trades> | reload | toggle | admin <add|remove> <player_name>"

permissions:
  kami.sama:
    description: "Allows usage of trademode command"
    default: op

