name: VillagerReputationTweaks
version: ${version}
main: com.kami.VillagerReputationTweaks
description: Gives several options for tweaking how villager reputations are managed for players on servers.
author: Kamisama
website: https://github.com/Ujjwal-Shekhawat
api-version: ${minecraft_version}

# Commands used by this
commands:
  trademode:
    description: "Get the trademode used on server"
